### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by DjebbZ** [leebyron/testcheck-js#14]
Hi,

Simple question : is the project still usable today ? Or do you know alternatives ?

Happy to see that you (again) took inspiration from the Clojure(Script) community.

By the way, we met at ReactEurope 2015. Cheers !

**Comment by leebyron** [comment]
Definitely still usable. It could use some minor maintenance but otherwise this has been an evergreen useful library since inception

**Comment by DjebbZ** [comment]
Even if late, thanks for the answer !
