### ISSUE TITLE
Collections generators failing

### ISSUE THREAD

**Issue by akrueger** [leebyron/testcheck-js#17]
Whenever I attempt any of the Collections generators (`array, object, arrayOrObject, nested`), I receive the following error:

e.g.

```
const testcheck = require('testcheck')
const gen = testcheck.gen
console.log(testcheck.sample(gen.array))
```

`TypeError: Cannot read property 'a' of null`

I'm using node `v7.0`

**Comment by akrueger** [comment]
Derp, just realized these take additional arguments and don't have a default. Closing.

**Comment by leebyron** [comment]
I'm going to reopen this as an error improvement task. Missing args should get clearer messages
