### ISSUE TITLE
Async checks

### ISSUE THREAD

**Issue by leebyron** [leebyron/testcheck-js#3]
A check should be able to run asynchronously, completing in a separate run tick. This would allow for more complete cross-compatibility with most test engines which support async tests.

Unfortunately right now, because it's based on clojure's testcheck, this feature probably needs to be added to testcheck first.

**Comment by leebyron** [comment]
Not going to happen

**Comment by trungdq88** [comment]
Is there any similar libraries that support async check? Can you suggest?
