### ISSUE TITLE
Published version of `testcheck` way behind docs?

### ISSUE THREAD

**Issue by scotttrinh** [leebyron/testcheck-js#33]
Sorry to blow up the issues, but I'm trying to get started using testcheck on a project, and keep running into issues! :)

Seems there has been 250 commits since last publish, and nothing seems to work quite like the docs say, for instance `gen.then` or `gen.notEmpty`. When I built from source, everything works fine. Is there something keeping the newer builds from being published to npm?

**Comment by MattMcFarland** [comment]
I agree. Some of the features documented are not working. For example, `{ numTests: 1000 }` does not change the number of test being run.

**Comment by emuvente** [comment]
Apparently only the docs in the release package should be used. The docs seem to be just for the (unreleased) master branch. See #31

**Comment by leebyron** [comment]
Sorry for the huge delay!

I just published v1.0.0-rc.0 which brings the npm released content up to date with the documentation!
