### ISSUE TITLE
Support of typed arrays?

### ISSUE THREAD

**Issue by Jabher** [leebyron/testcheck-js#40]
IDK about others, but I would be definitely happy to see a generator for Typed Arrays (uint8, float32, etc) with length as provided option.

**Comment by leebyron** [comment]
There's no plan to add these to the library, however it should be very easy to add this directly to your tests with the existing API with a one-liner:

```js
// Generate of varying lengths
gen.array(gen.int).then(arr => new Int32Array(arr))
```
