### ISSUE TITLE
_checkPlanCount is undefined

### ISSUE THREAD

**Issue by Alxandr** [leebyron/testcheck-js#44]
`__checkPlanCount` in ava is undefined, which leads to tests failing.

However, you have `assertCount` and `planCount` available (might be `plannedCount`, just remember there was one).

**Comment by Alxandr** [comment]
`sync` is also not a value.

**Comment by leebyron** [comment]
Would love some help with a PR fixing this

**Comment by vincenting** [comment]
It seems that `__checkPlanCount` has been renamed to `verifyPlan`.

https://github.com/avajs/ava/commit/4463f38605929071f2ae611715a0e26c7375ccff#diff-dd2e881af3311f834199c7b515cff0c7L312
https://github.com/avajs/ava/blob/master/lib/test.js#L227

It will make my tests work, but I'm not sure it will work successfully for everyone.

**Comment by danr** [comment]
Fixed in #63
