### ISSUE TITLE
Support for async properties

### ISSUE THREAD

**Issue by akiellor** [leebyron/testcheck-js#45]
I'd like to write properties asynchronous behaviours. My understanding is that testcheck-js doesn't support itat the moment (at least the mocha bridge).

**Comment by leebyron** [comment]
Unfortunately that would require a complete overhaul of the test runner itself, which expects a synchronous function. It's not possible right now.

**Comment by gasi** [comment]
+1 for this feature so we could test async functions in testcheck properties.

**Comment by leebyron** [comment]
Opening this issue to track the demand, however it is still not possible and there are no current plans to build this support.

(Perhaps a great task for someone who wants to take on a challenging PR)

**Comment by davidnormo** [comment]
I've had a little play: #73, feedback welcome!
