### ISSUE TITLE
Custom generator and shrinking

### ISSUE THREAD

**Issue by davidnormo** [leebyron/testcheck-js#46]
I don't think this functionality exists but is there currently a way to create a new generator type with custom shrinking behaviour?

**Comment by leebyron** [comment]
Yes! You probably want to use [`.then()`](http://leebyron.com/testcheck-js/api#generatorthen) to create new custom generators.

In fact, the only native generator in this library is for positive integers which shrinks towards 0, and all other generators are derived from that one.

**Comment by davidnormo** [comment]
Yep I've been using that but I don't seem to be able to get the kind of shrinking behaviour I need. Basically I need access to `gen/gen-pure` in some way so I can provide a rose tree and create a generator from it. 

Perhaps adding to the Generator protocol a `shrink` function that takes a generated value and returns an array of shrunken values?
