### ISSUE TITLE
How to access `done` in jasmine-check

### ISSUE THREAD

**Issue by puneetar** [leebyron/testcheck-js#49]
Hi, 

How could I access `done` function to test async functionality in jasmine-check? 
 https://jasmine.github.io/2.0/introduction.html#section-Asynchronous_Support

``` 
it("takes a long time", gen.int,  function(int1, done) {
      setTimeout(function() {
       //  .. use int1 ...
        done();
      }, 9000);
    });
```

Is it supported currently?

Thanks

**Comment by imranolas** [comment]
Sadly not. https://github.com/leebyron/testcheck-js/issues/45#issuecomment-307527859

**Comment by garbles** [comment]
@imranolas @puneetar https://github.com/leebyron/testcheck-js/pull/54

**Comment by leebyron** [comment]
Merging into #45
