### ISSUE TITLE
Generate functions?

### ISSUE THREAD

**Issue by cangoektas** [leebyron/testcheck-js#50]
Hi,

just read through the docs and didn't see a way to generate functions. What's the reason for that? Always wanted to try out this library but I have a higher order function I'd like to test with it. Not sure if this is something this project was intended for. 😄

**Edit:** Just to clarify, I was hoping there was a way to generate functions that not just return random data but with JS-specifics like different `this` bindings, function expressions vs. function declarations, async functions, functions that crash etc.

Thanks!

**Comment by leebyron** [comment]
This isn't included since every test is likely to want something different. I suggest using `gen.oneOf` for picking different kinds of functions of `.then(val => () => val)` to convert a generator of a value to a generator of a function that returns that value.
