### ISSUE TITLE
jasmine-check and Jest

### ISSUE THREAD

**Issue by rhythnic** [leebyron/testcheck-js#51]
I'm trying to use jasmine-check with Jest and I'm getting the error caused by jasmine not being a global variable.  Is Jasmine required to use jasmine-check with Jest?

**Comment by JM-Mendez** [comment]
I'm running it on jest without jasmine installed. I just add the global require up top, and it worked. Typescript complains tho, but it still runs tests.

**Comment by garbles** [comment]
If you attempt to require this library too early in the boot process, you will see this error. @rhythnic where are you first calling it?

**Comment by rhythnic** [comment]
I'm sorry I can't be more help.  I don't remember how I had it configured when it wasn't working.  Good news is that it's working well now.  I forgot that I had created this issue, but I'll close it now.
