### ISSUE TITLE
Shrinking?

### ISSUE THREAD

**Issue by spontaliku-softaria** [leebyron/testcheck-js#55]
Does testcheck-js support shrinking? I don't see any docs on it. I think it would be very useful feature, and I guess most of users expect QuickCheck-like tool to have it.
I had nice experience with [quickcheckjs](https://quickcheckjs.readme.io/) - it does some shrinking itself and also allows to add custom shrinkers. As far as docs states, [jsverify](https://github.com/jsverify/jsverify) has shrinking too.

**Comment by honzabrecka** [comment]
Yes, of course it does - http://leebyron.com/testcheck-js/#smallest-failing-test

**Comment by spontaliku-softaria** [comment]
Sorry, I've missed that part of docs.
