### ISSUE TITLE
feature request: gen.float

### ISSUE THREAD

**Issue by JamieMason** [leebyron/testcheck-js#59]
I wondered what your thoughts were on adding `gen.float`, or if you could recommend what the best approach might be for me achieving this using what is already available.

I'm looking for a generator similar to `gen.number` but that only generates numbers with decimal places, rather than a mixture of whole numbers and those with decimal places.

Feel free to close if I'm on the wrong track, thanks for your time.

**Comment by leebyron** [comment]
`gen.number` is definitely what you're looking for with respect to providing numbers that can include a decimal part. It's synonymous with `gen.float`.

If you want to explicitly exclude those where the decimal part happens to be 0, try `gen.number.suchThat(num => num % 1 !== 0)`
