### ISSUE TITLE
gen.uniqueArray() repeats undefined and null

### ISSUE THREAD

**Issue by bholloway** [leebyron/testcheck-js#60]
Loving the property testing. Thanks for your library and catering for `tape`.

Just playing with this generator. It seams that `null` and `undefined` are being repeated.
```javascript
gen.uniqueArray(gen.primitive, {size: ...})
```

I am unfamiliar with Clojure. However I imagine that maybe both are considered `nil` and `nil` never matches itself? My workaround is this...
```javascript
const undef = Symbol('undefined');
const nul = Symbol('null');
const uniqueFn = v => ((v === undefined) ? undef : (v === null) ? nul : v);
...
gen.uniqueArray(gen.primitive, uniqueFn, {size: ...})
```
Is this a known issue? Maybe the default unique fn needs to be adjusted for the quirks of Javascript.

**Comment by leebyron** [comment]
You're totally correct, thanks for the bug report!
