### ISSUE TITLE
Add global testcheck variables on the docs site for easy interaction in dev tools

### ISSUE THREAD

**Issue by wdoug** [leebyron/testcheck-js#62]
Many javascript libraries add their exports as global variables on their docs site. This makes it easy to pop open the console and test out different methods of the library in a repl right next to the actual docs. This would be super useful to quickly test out sampling different generators, etc.

I would personally love to have each of the top level exports (`check`, `property`, `sample`, `sampleOne`, `gen`, `Generator`) be added to `window` since that is how they will commonly be used. Something indicating that those variables are globally defined would also be nice such as how the `Immutable.js` docs site log some initial info showing that `Immutable` is globally defined.

**Comment by leebyron** [comment]
Good suggestion - wasn't too hard to put together :)
