### ISSUE TITLE
ava-check inadvertently thinks tests are async and fails

### ISSUE THREAD

**Issue by syzer** [leebyron/testcheck-js#75]
the example test fails
```js
const test = require('ava')
const { check, gen } = require('ava-check')

test('addition is commutative', check(gen.int, gen.int, (t, numA, numB) => {
  t.true(numA + numB === numB + numA)
}))
```
 TypeError {
    message: 'ava-check cannot check tests with async assertions.',
  }

**Comment by syzer** [comment]
```  "devDependencies": {
    "ava": "^1.0.0-beta.3",
    "testcheck": "^1.0.0-rc.2"
  },
  "dependencies": {
    "ava-check": "^1.0.0-rc.0",
    "natural": "^0.5.6",
    "nodemon": "^1.17.2"
  }```

**Comment by leebyron** [comment]
Thanks for the report. I think this works with older versions of Ava and broke in a recent new version of Ava. We got this fixed in #48 which merged the other day, and I'll have a new release shortly.

**Comment by syzer** [comment]
![power-of-open-source](https://user-images.githubusercontent.com/1989646/37793868-2527c12e-2e10-11e8-856f-bd2a4c4dddad.jpg)

**Comment by leebyron** [comment]
Sometimes we're just all in the right place at the right time :) thanks for using testcheck!
