### ISSUE TITLE
Requiring externally seems to break

### ISSUE THREAD

**Issue by dbousamra** [leebyron/testcheck-js#9]
Excuse the poor title. Not sure how to describe this behaviour.

I have an internal npm package 'example-generators', that exposes a generators.js file like so:

``` javascript
var testcheck = require('testcheck');
var gen = testcheck.gen;
exports.genBoolean = gen.returnOneOf([true, false]);
```

In another node project, I have a single source file, test.js, where I require('example-generators') like so:

``` javascript
var testcheck = require('testcheck')
var generators = require('example-generators')
```

I then call:

``` javascript
var bools = testcheck.sample(generators.genBoolean)
```

and am greeted with:

``` shell
return a.a ? a.a(b, c) : a.call(null, b, c)
│TypeError: Cannot read property 'a' of null
    at Function.Gg (/Users/Dom/Code/some-code/node_modules/testcheck/dist/testcheck.js:6699:21)
```

This is odd. It seems to stem from the require in the generators.js file. If I modify generators.ts to look like so:

``` javascript
var testcheck = require('/Users/Dom/Code/some-code/node_modules/testcheck/dist/testcheck.js');
var gen = testcheck.gen;
exports.genBoolean = gen.returnOneOf([true, false]);
```

I.e. use the same testcheck.js install. It seems to work. I have no idea what is going on, given we are dealing with minified clj -> js, I can't gain much insight.

Any ideas?

**Comment by leebyron** [comment]
Cleaning out tasks on this repo, sorry for letting these sit.

My instinct is that this was including two copies of testcheck, this can happen if two npm packages require different versions of the library
